Add transaction date. Add readme.md. Modify dockerfile.
openpaymentseurope/docs pull request #41
Opened 2020-11-13 11:01 UTC by nikolaykrondev

You can see how readme looks like directly into the branch: https://github.com/openpaymentseurope/docs/tree/feature/add-transaction-date

2020-11-13 14:39 UTC, henrikwidlund requested changes
Looks good, but please have a look at my comments :)

2020-11-13 14:39 UTC, henrikwidlund commented on apiref/openpayments-NextGenPSD2-1.3.3.yaml
> +      description: The transaction date is the date the transaction was originally performed.
Where did this description come from?

2020-11-13 14:39 UTC, henrikwidlund commented on Dockerfile
> +RUN mv /app/website/redoc-static.html /app/website/pages/en/openpayments-NextGenPSD2-1.3.3.html
Has this been checked with @janeklof so that it is correct in regards to what he did before manually?

2020-11-13 14:39 UTC, henrikwidlund commented on readme.md
> +```
Not sure if this should be in our public repo?

2020-11-13 14:40 UTC, nikolaykrondev commented on apiref/openpayments-NextGenPSD2-1.3.3.yaml
> +      description: The transaction date is the date the transaction was originally performed.
From conversation with Peter and Janne

2020-11-13 14:41 UTC, nikolaykrondev commented on Dockerfile
> +RUN mv /app/website/redoc-static.html /app/website/pages/en/openpayments-NextGenPSD2-1.3.3.html
Well, "it works on my machine" :) but I added him manually as a reviewer to this PR

2020-11-13 14:42 UTC, nikolaykrondev commented on readme.md
> +```
Argh, right, I forgot that this repo is public, I can move the whole readme to our Wiki in AzureDevops

2020-11-13 14:43 UTC, henrikwidlund commented on Dockerfile
> +RUN mv /app/website/redoc-static.html /app/website/pages/en/openpayments-NextGenPSD2-1.3.3.html
Cool, let's wait for his response before resolving this comment

2020-11-13 14:44 UTC, henrikwidlund commented on readme.md
> +```
Yeah, might be a better place for it 👍

2020-11-16 12:46 UTC, janeklof commented on Dockerfile
> +RUN mv /app/website/redoc-static.html /app/website/pages/en/openpayments-NextGenPSD2-1.3.3.html
@nikolaykrondev the resulting html file from the ReDoc generation step also needs to be checked in as docs/website/pages/en/openpayments-NextGenPSD2-1.3.3.html

2020-11-17 09:10 UTC, henrikwidlund commented on Dockerfile
> +RUN mv /app/website/redoc-static.html /app/website/pages/en/openpayments-NextGenPSD2-1.3.3.html
Fixed in #42

2020-11-17 09:11 UTC, henrikwidlund approved these changes

2020-11-18 15:37 UTC, nikolaykrondev commented
I close this one since we do not go anywhere with transaction date at the moment.
Created another PR #43 that refreshes docusaurus branch with latest changes

2020-11-18 15:37 UTC, closed without merging