Make banks more linky
openpaymentseurope/docs pull request #94
Opened 2021-12-08 10:04 UTC by pontusope

Customers don't understand that they can click the bank name to go to the page for that bank (or that there is such as page). After request from product, there is now another link under the name with different style to highlight the fact that they can click it.

2021-12-08 10:13 UTC, henrikwidlund approved these changes
LGTM

2021-12-09 15:18 UTC, janeklof approved these changes

2021-12-09 15:32 UTC, henrikwidlund requested changes
This PR needs to be updated with changes in master so we don't overwrite changes there. You must also create a new version of the docs for the changes to appear. As of writing this the latest version is 1.0.30

2021-12-14 12:43 UTC, henrikwidlund approved these changes

2021-12-14 14:05 UTC, merged